# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Repocheck < Formula
  desc ""
  homepage ""
  version "0.5.1-alpha"

  on_macos do
    url "https://github.com/bevane/repocheck/releases/download/v0.5.1-alpha/repocheck_Darwin_all.tar.gz"
    sha256 "ea2ce9d61fad8d8feb8b84533aaa6b08bd8aad18b3de48ffaae346db79a815dc"

    def install
      bin.install "repocheck"
      bash_completion.install "completions/repocheck.bash" => "repocheck"
      zsh_completion.install "completions/repocheck.zsh" => "_repocheck"
      fish_completion.install "completions/repocheck.fish"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bevane/repocheck/releases/download/v0.5.1-alpha/repocheck_Linux_x86_64.tar.gz"
        sha256 "657402744864ce47c7b841d18f2c0fa34dd618c4dcd0934758f8532f2ff9e91a"

        def install
          bin.install "repocheck"
          bash_completion.install "completions/repocheck.bash" => "repocheck"
          zsh_completion.install "completions/repocheck.zsh" => "_repocheck"
          fish_completion.install "completions/repocheck.fish"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bevane/repocheck/releases/download/v0.5.1-alpha/repocheck_Linux_arm64.tar.gz"
        sha256 "59da69beb4b3682ca0dbc89fc7d67b01547719857e7c0fd4ee44d269b9fbc785"

        def install
          bin.install "repocheck"
          bash_completion.install "completions/repocheck.bash" => "repocheck"
          zsh_completion.install "completions/repocheck.zsh" => "_repocheck"
          fish_completion.install "completions/repocheck.fish"
        end
      end
    end
  end
end
