# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Repocheck < Formula
  desc ""
  homepage ""
  version "1.0.3"

  on_macos do
    url "https://github.com/bevane/repocheck/releases/download/v1.0.3/repocheck_Darwin_all.tar.gz"
    sha256 "2b171c7e20b7bbc14f715de3b4c6ea7810732d40978881e5ccae431a18b13c08"

    def install
      bin.install "repocheck"
      bash_completion.install "completions/repocheck.bash" => "repocheck"
      zsh_completion.install "completions/repocheck.zsh" => "_repocheck"
      fish_completion.install "completions/repocheck.fish"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bevane/repocheck/releases/download/v1.0.3/repocheck_Linux_x86_64.tar.gz"
        sha256 "dd2f0431e7fbb42af98e81a8b0bc3c61fcc651d3f02890d0429b6ac18f1eade0"

        def install
          bin.install "repocheck"
          bash_completion.install "completions/repocheck.bash" => "repocheck"
          zsh_completion.install "completions/repocheck.zsh" => "_repocheck"
          fish_completion.install "completions/repocheck.fish"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bevane/repocheck/releases/download/v1.0.3/repocheck_Linux_arm64.tar.gz"
        sha256 "62d1e54bdbe30b144cd893b37c698364efe8b04126e9007f3b205d41fea7448c"

        def install
          bin.install "repocheck"
          bash_completion.install "completions/repocheck.bash" => "repocheck"
          zsh_completion.install "completions/repocheck.zsh" => "_repocheck"
          fish_completion.install "completions/repocheck.fish"
        end
      end
    end
  end
end
